version: '3'
services:
  bot:
    build: .
    command: python bot.py
    image: poker-night-bot:latest  # תן שם לתמונה
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase


  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - /data/db

