version: "3.3"

services:
  mongo:
    image: mongo:5.0
    command: --tlsMode disabled
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootrootֿֿ

  bot:
    image: python:3.9
    working_dir: /app
    volumes:
      - .:/app
    command: python bot.py  # מחליף ל- bot.py את שם הסקריפט
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase  # הגדרת חיבור למונגו

volumes:
  mongo_data:

